org.gradle.jvmargs=-Xmx1024m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
org.gradle.daemon=false
org.gradle.workers.max=2
org.gradle.parallel=false
org.gradle.caching=true
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.compiler.execution.strategy=in-process
android.aapt2FromMavenOverride=/workspace/toolchain/bin/aapt2
